# dbt profile for Dune API connection
# CHANGE THIS: Set 'schema' to your team name (lines 14, 29)
dbt_template:
  target: dev
  outputs:
    dev:
      type: trino
      user: dune # do not change: user is always 'dune'
      password: "{{ env_var('DBT_TEMPLATE_API_KEY') }}"
      host: dune-api-trino.dev.dune.com
      port: 443
      method: ldap
      catalog: dune # do not change: catalog is always 'dune'
      schema: dune  # CHANGE THIS: Set to your Dune team name
      threads: 4
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC
    prod:
      type: trino
      user: dune # do not change: user is always 'dune'
      password: "{{ env_var('DBT_TEMPLATE_API_KEY') }}"
      host: dune-api-trino.dune.com
      port: 443
      method: ldap
      catalog: dune # do not change: catalog is always 'dune'
      schema: dune  # CHANGE THIS: Set to your team name
      threads: 4
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC