# old config, to be removed when API profile is fully tested
dbt_template:
  target: prod
  outputs:
    prod:
      type: trino
      user: "{{ env_var('DBT_TEMPLATE_USER') }}"
      password: "{{ env_var('DBT_TEMPLATE_PASSWORD') }}"
      host: "{{ env_var('DBT_TEMPLATE_HOST') }}"
      port: 443
      method: ldap
      database: hive
      schema: "{{ env_var('DBT_TEMPLATE_SCHEMA') }}"
      threads: 4
      http_scheme: https
      cert: true
      http_headers:
        X-Trino-Routing-Group: "{{ env_var('DBT_TEMPLATE_ROUTING_GROUP') }}"
        X-Forwarded-Proto: https
        X-Trino-Extra-Credential: "dune={{ env_var('DBT_TEMPLATE_EXTRA_CREDENTIAL') }}"
      session_properties:
        query_max_run_time: 12h
      timezone: UTC

# new config, dune connectivity, api
dbt_template_api:
  target: prod
  outputs:
    prod:
      type: trino
      user: "{{ env_var('DBT_TEMPLATE_API_USER') }}"
      password: "{{ env_var('DBT_TEMPLATE_API_KEY') }}"
      host: "{{ env_var('DBT_TEMPLATE_API_HOST') }}"
      port: 443
      method: ldap
      catalog: "{{ env_var('DBT_TEMPLATE_API_CATALOG') }}"
      schema: "{{ env_var('DBT_TEMPLATE_API_SCHEMA') }}"
      threads: 4
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC