# dbt profile for Dune API connection
dbt_template:
  target: dev # default to dev for local development
  outputs:
    dev:
      type: trino
      user: "{{ env_var('DBT_TEMPLATE_USER') }}"
      password: "{{ env_var('DBT_TEMPLATE_API_KEY') }}"
      host: "{{ env_var('DBT_TEMPLATE_HOST') }}"
      port: 443
      method: ldap
      catalog: "{{ env_var('DBT_TEMPLATE_CATALOG') }}"
      schema: "{{ env_var('DBT_TEMPLATE_SCHEMA') }}"
      threads: 4
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC
    prod:
      type: trino
      user: "{{ env_var('DBT_TEMPLATE_USER') }}"
      password: "{{ env_var('DBT_TEMPLATE_API_KEY') }}"
      host: "{{ env_var('DBT_TEMPLATE_HOST') }}"
      port: 443
      method: ldap
      catalog: "{{ env_var('DBT_TEMPLATE_CATALOG') }}"
      schema: "{{ env_var('DBT_TEMPLATE_SCHEMA') }}"
      threads: 4
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC
