name: dbt manifest refresh

# Periodically refreshes the manifest artifact to prevent 90-day expiration.
# Only downloads and re-uploads the existing artifact to reset the retention timer.

on:
  schedule:
    - cron: '0 0 1 * *'  # Run on the 1st of every month at midnight UTC
  workflow_dispatch:  # Allow manual triggers

concurrency:
  group: dbt-prod-runs  # Shared group with dbt_deploy.yml and dbt_prod.yml
  cancel-in-progress: false  # Don't cancel in-progress runs, queue instead

jobs:
  dbt-manifest-refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Download current manifest
        uses: dawidd6/action-download-artifact@v6
        with:
          name: prod-manifest-latest
          path: ./manifest
          workflow: dbt_deploy.yml
          branch: main
          if_no_artifact_found: fail

      - name: Re-upload manifest to refresh retention
        uses: actions/upload-artifact@v4
        with:
          name: prod-manifest-latest
          path: manifest/manifest.json
          retention-days: 90
          overwrite: true

      - name: Confirmation
        run: echo "✅ Manifest artifact retention refreshed for another 90 days"

