name: dbt CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'models/**'
      - 'macros/**'
      - 'dbt_project.yml'
      - 'profiles.yml'
      - 'packages.yml'
      - '.github/workflows/dbt_run.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      DUNE_TEAM_NAME: ${{ vars.DUNE_TEAM_NAME || 'dune' }}  # Set as GitHub Variable or defaults to 'dune'
      DEV_SCHEMA_SUFFIX: pr${{ github.event.pull_request.number }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Install dbt packages
        run: uv run dbt deps

      - name: Check if manifest artifact exists
        id: check-artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Check if the artifact exists in the dbt_manifest_build workflow
          if gh run list --workflow=dbt_manifest_build.yml --branch=main --status=completed --limit=1 --json databaseId | grep -q databaseId; then
            echo "artifact_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Manifest artifact found"
          else
            echo "artifact_exists=false" >> $GITHUB_OUTPUT
            echo "⚠️  No manifest artifact found - will trigger manifest build workflow"
          fi

      - name: Trigger manifest build workflow if needed
        if: steps.check-artifact.outputs.artifact_exists == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "🔄 Triggering dbt manifest build workflow..."
          gh workflow run dbt_manifest_build.yml --ref main
          
          echo "⏳ Waiting for workflow to start..."
          sleep 10
          
          echo "⏳ Waiting for manifest build to complete (this may take several minutes)..."
          gh run watch $(gh run list --workflow=dbt_manifest_build.yml --branch=main --limit=1 --json databaseId --jq '.[0].databaseId') --exit-status

      - name: Download main branch manifest
        # Using dawidd6/action-download-artifact instead of actions/download-artifact
        # because the official action only downloads artifacts from the same workflow run,
        # while we need to download the manifest from a different workflow (dbt_manifest_build).
        uses: dawidd6/action-download-artifact@v6
        with:
          name: prod-manifest-latest
          path: ./state
          workflow: dbt_manifest_build.yml
          branch: main

      - name: Compile feature branch models
        run: uv run dbt compile

      - name: Run modified models (full refresh)
        run: uv run dbt run --select state:modified --state ./state --full-refresh

      - name: Test modified models (after full refresh)
        run: uv run dbt test --select state:modified --state ./state
  
      - name: Run modified incremental models (incremental run)
        run: uv run dbt run --select state:modified,config.materialized:incremental --state ./state

      - name: Test modified incremental models (after incremental run)
        run: uv run dbt test --select state:modified,config.materialized:incremental --state ./state