name: dbt manifest build

on:
  push:
    branches:
      - main
    paths:
      - 'models/**'
      - 'macros/**'
      - 'dbt_project.yml'
      - 'profiles.yml'
      - 'packages.yml'
      - '.github/workflows/dbt_manifest_build.yml'
  workflow_dispatch:  # Allow manual triggers

concurrency:
  group: dbt-prod-runs  # Shared group with dbt_prod.yml to prevent concurrent production runs
  cancel-in-progress: false  # Don't cancel in-progress runs, queue instead

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      DUNE_TEAM_NAME: ${{ vars.DUNE_TEAM_NAME || 'dune' }}  # Set as GitHub Variable or defaults to 'dune'
      DBT_TARGET: prod  # All dbt commands will use the prod target from profiles.yml
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Install dbt packages
        run: uv run dbt deps

      - name: Download previous manifest for state comparison
        id: download-manifest
        continue-on-error: true
        # Using dawidd6/action-download-artifact instead of actions/download-artifact
        # because the official action only downloads artifacts from the same workflow run,
        # while we need to download the manifest from the previous run of this workflow.
        uses: dawidd6/action-download-artifact@v6
        with:
          name: prod-manifest-latest
          path: ./state
          workflow: dbt_manifest_build.yml
          branch: main
          if_no_artifact_found: warn

      - name: Compile current models
        run: uv run dbt compile

      - name: Determine if previous state exists
        id: check-state
        run: |
          if [ -f "./state/manifest.json" ]; then
            echo "state_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Previous manifest found - will run modified models only"
          else
            echo "state_exists=false" >> $GITHUB_OUTPUT
            echo "⚠️  No previous manifest found - will run all models (first run or artifact expired)"
          fi

      - name: Run modified models with full refresh
        if: steps.check-state.outputs.state_exists == 'true'
        run: uv run dbt run --select state:modified+ --state ./state --full-refresh

      - name: Test modified models
        if: steps.check-state.outputs.state_exists == 'true'
        run: uv run dbt test --select state:modified+ --state ./state

      - name: Run all models (first run or no previous state)
        if: steps.check-state.outputs.state_exists == 'false'
        run: uv run dbt run --exclude config.materialized:view # views should only run when modified

      - name: Test all models (first run or no previous state)
        if: steps.check-state.outputs.state_exists == 'false'
        run: uv run dbt test

      - name: Upload current manifest for next run
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: prod-manifest-latest
          path: target/manifest.json
          retention-days: 90
          overwrite: true # overwrite the artifact with the latest manifest, ensures only one artifact is uploaded

