name: dbt CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      DBT_PROFILES_DIR: .
      DBT_TARGET: dev
      DBT_TEMPLATE_USER: dune
      DBT_TEMPLATE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      DBT_TEMPLATE_HOST: ${{ secrets.DUNE_HOST }}
      DBT_TEMPLATE_CATALOG: dune
      DBT_TEMPLATE_SCHEMA: ${{ secrets.DUNE_SCHEMA }}
      DEV_SCHEMA_SUFFIX: pr${{ github.event.pull_request.number }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Install dbt packages
        run: uv run dbt deps

      - name: Compile models
        run: uv run dbt compile

      - name: Run models (full refresh)
        run: uv run dbt run --full-refresh

      - name: Test models (after full refresh)
        run: uv run dbt test
  
      - name: Run models (incremental)
        run: uv run dbt run

      - name: Test models (after incremental)
        run: uv run dbt test
