name: dbt manifest generate

# Lightweight workflow that only compiles and generates the manifest artifact.
# Used by CI when no manifest exists yet, or can be manually triggered.

on:
  workflow_call:  # Can be called by other workflows
  workflow_dispatch:  # Can be manually triggered

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      DUNE_TEAM_NAME: ${{ vars.DUNE_TEAM_NAME || 'dune' }}
      DBT_TARGET: prod
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Install dbt packages
        run: uv run dbt deps

      - name: Compile models
        run: uv run dbt compile

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: prod-manifest-latest
          path: target/manifest.json
          retention-days: 90
          overwrite: true

